-- MySQL Script generated by MySQL Workbench
-- Wed Feb  8 01:36:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema ticket_booking_system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ticket_booking_system` ;

-- -----------------------------------------------------
-- Schema ticket_booking_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticket_booking_system` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `ticket_booking_system` ;

-- -----------------------------------------------------
-- Table `account_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account_role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `account_role` (
  `id` INT(11) UNSIGNED NOT NULL,
  `account_id` INT(11) UNSIGNED NOT NULL,
  `role_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `role_id_idx` ON `account_role` (`role_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `account_id_idx` ON `account_role` (`account_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `accounts` (
  `id` INT(11) UNSIGNED NOT NULL,
  `username` VARCHAR(55) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `account_user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account_user_profile` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `account_user_profile` (
  `id` INT(11) UNSIGNED NOT NULL,
  `account_id` INT(11) UNSIGNED NOT NULL,
  `user_profile_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_profile_id`
    FOREIGN KEY (`user_profile_id`)
    REFERENCES `user_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `account_id_idx` ON `account_user_profile` (`account_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_profile_id_idx` ON `account_user_profile` (`user_profile_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `booked_seats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booked_seats` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `booked_seats` (
  `id` INT(11) UNSIGNED NOT NULL,
  `booking_id` INT(11) UNSIGNED NOT NULL,
  `row` INT(11) NOT NULL,
  `column` INT(11) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `booking_id`
    FOREIGN KEY (`booking_id`)
    REFERENCES `bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `booking_id_idx` ON `booked_seats` (`booking_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `booking_payment_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booking_payment_details` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `booking_payment_details` (
  `id` INT(11) UNSIGNED NOT NULL,
  `booking_id` INT(11) UNSIGNED NOT NULL,
  `base_price` DECIMAL(10,2) NOT NULL,
  `discount` DECIMAL(10,2) NULL DEFAULT NULL,
  `discount_code` VARCHAR(45) NULL DEFAULT NULL,
  `gst_amount` DECIMAL(10,2) NOT NULL,
  `other_fee` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `booking_id`
    FOREIGN KEY (`booking_id`)
    REFERENCES `bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `booking_id_idx` ON `booking_payment_details` (`booking_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookings` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bookings` (
  `id` INT(11) UNSIGNED NOT NULL,
  `movie_id` INT(11) UNSIGNED NOT NULL,
  `section_id` INT(11) UNSIGNED NOT NULL,
  `show_timing_id` INT(11) UNSIGNED NOT NULL,
  `theatre_hall_id` INT(11) UNSIGNED NOT NULL,
  `theatre_id` INT(11) UNSIGNED NOT NULL,
  `location_id` INT(10) UNSIGNED NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL,
  `payment_transaction_number` VARCHAR(100) NULL DEFAULT NULL,
  `qr_code_url` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `section_id`
    FOREIGN KEY (`section_id`)
    REFERENCES `sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `show_timing_id`
    FOREIGN KEY (`show_timing_id`)
    REFERENCES `show_timings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `theatre_hall_id`
    FOREIGN KEY (`theatre_hall_id`)
    REFERENCES `theatre_halls` (`theatre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `theatre_id`
    FOREIGN KEY (`theatre_id`)
    REFERENCES `theatre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `user_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `movie_id_idx` ON `bookings` (`movie_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `section_id_idx` ON `bookings` (`section_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `show_timing_id_idx` ON `bookings` (`show_timing_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `theatre_hall_id_idx` ON `bookings` (`theatre_hall_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `theatre_id_idx` ON `bookings` (`theatre_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `location_id_idx` ON `bookings` (`location_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_id_idx` ON `bookings` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `booking_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booking_status` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `booking_status` (
  `id` INT(11) UNSIGNED NOT NULL,
  `booking_id` INT(11) UNSIGNED NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `booking_id`
    FOREIGN KEY (`booking_id`)
    REFERENCES `bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `booking_id_idx` ON `booking_status` (`booking_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `certificates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `certificates` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `certificates` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genres` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `genres` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `languages` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `languages` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `locations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `address_line_1` VARCHAR(255) NOT NULL,
  `address_line_2` VARCHAR(255) NULL DEFAULT NULL,
  `unit_block_number` VARCHAR(45) NULL DEFAULT NULL,
  `zipcode` VARCHAR(15) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `latitude` DECIMAL(10,8) NULL DEFAULT NULL,
  `longitude` DECIMAL(11,8) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `movie_certifcate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_certifcate` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `movie_certifcate` (
  `id` INT(11) UNSIGNED NOT NULL,
  `movie_id` INT(11) UNSIGNED NOT NULL,
  `certificate_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `certification_id`
    FOREIGN KEY (`certificate_id`)
    REFERENCES `certificates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `movie_id_idx` ON `movie_certifcate` (`movie_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `certification_id_idx` ON `movie_certifcate` (`certificate_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `movie_genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_genre` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `movie_genre` (
  `id` INT(11) UNSIGNED NOT NULL,
  `movie_id` INT(11) UNSIGNED NOT NULL,
  `genre_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `genre_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `movie_id_idx` ON `movie_genre` (`movie_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `genre_id_idx` ON `movie_genre` (`genre_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `movie_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_language` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `movie_language` (
  `id` INT(11) UNSIGNED NOT NULL,
  `movie_id` INT(11) UNSIGNED NOT NULL,
  `language_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `movie_id_idx` ON `movie_language` (`movie_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `language_id_idx` ON `movie_language` (`language_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `movies` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `movie_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `movie_tag` (
  `id` INT(11) UNSIGNED NOT NULL,
  `movie_id` INT(11) UNSIGNED NOT NULL,
  `tag_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag_id`
    FOREIGN KEY (`tag_id`)
    REFERENCES `tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `movie_id_idx` ON `movie_tag` (`movie_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tag_id_idx` ON `movie_tag` (`tag_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `offers` (
  `id` INT(11) UNSIGNED NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `theatre_id` INT(10) UNSIGNED NOT NULL,
  `theatre_hall_id` INT(10) UNSIGNED NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `offer_show_timings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offer_show_timings` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `offer_show_timings` (
  `id` INT(11) UNSIGNED NOT NULL,
  `offer_id` INT(11) UNSIGNED NOT NULL,
  `show_timing_id` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `offer_id`
    FOREIGN KEY (`offer_id`)
    REFERENCES `offers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `show_timing_id`
    FOREIGN KEY (`show_timing_id`)
    REFERENCES `show_timings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `offer_id_idx` ON `offer_show_timings` (`offer_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `show_timing_id_idx` ON `offer_show_timings` (`show_timing_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `payment_transaction_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_transaction_details` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `payment_transaction_details` (
  `id` INT(11) UNSIGNED NOT NULL,
  `transaction_reference_number` VARCHAR(100) NOT NULL,
  `mode_of_payment` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `booking_id` INT(11) UNSIGNED NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `service_provider` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `booking_id`
    FOREIGN KEY (`booking_id`)
    REFERENCES `bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `booking_id_idx` ON `payment_transaction_details` (`booking_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `label` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `seating_plans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seating_plans` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `seating_plans` (
  `id` INT(11) UNSIGNED NOT NULL,
  `theatre_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `theatre_id`
    FOREIGN KEY (`theatre_id`)
    REFERENCES `theatre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `theatre_id_idx` ON `seating_plans` (`theatre_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sections` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sections` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `size` INT(11) NOT NULL,
  `rows` INT(11) NOT NULL,
  `columns` INT(11) NOT NULL,
  `prefix` VARCHAR(45) NULL DEFAULT NULL,
  `suffix` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `seating_plan_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `shows`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shows` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `shows` (
  `id` INT(10) UNSIGNED NOT NULL,
  `location_id` INT(10) UNSIGNED NOT NULL,
  `movie_id` INT(10) UNSIGNED NOT NULL,
  `description` TEXT NOT NULL,
  `theatre_id` INT(10) UNSIGNED NOT NULL,
  `theatre_hall_id` INT(10) UNSIGNED NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `theatre_id`
    FOREIGN KEY (`theatre_id`)
    REFERENCES `theatre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `theatre_hall_id`
    FOREIGN KEY (`theatre_hall_id`)
    REFERENCES `theatre_halls` (`theatre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `location_id_idx` ON `shows` (`location_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `movie_id_idx` ON `shows` (`movie_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `theatre_id_idx` ON `shows` (`theatre_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `theatre_hall_id_idx` ON `shows` (`theatre_hall_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `show_section_show_timing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `show_section_show_timing` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `show_section_show_timing` (
  `id` INT(11) UNSIGNED NOT NULL,
  `show_id` INT(11) UNSIGNED NOT NULL,
  `section_id` INT(11) UNSIGNED NOT NULL,
  `show_timing_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `show_id`
    FOREIGN KEY (`show_id` , `section_id`)
    REFERENCES `shows` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `section_id`
    FOREIGN KEY ()
    REFERENCES `sections` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `show_timing_id`
    FOREIGN KEY (`show_timing_id`)
    REFERENCES `show_timings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `show_id_idx` ON `show_section_show_timing` (`show_id` ASC, `section_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `show_timing_id_idx` ON `show_section_show_timing` (`show_timing_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `show_timings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `show_timings` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `show_timings` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `hour_timer` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tags` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tags` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `theatre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theatre` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `theatre` (
  `id` INT(11) UNSIGNED NOT NULL,
  `theatre_partner_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `contact_number` VARCHAR(20) NOT NULL,
  `description` TEXT NOT NULL,
  `location_id` INT(11) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `theatre_partner_id`
    FOREIGN KEY (`theatre_partner_id`)
    REFERENCES `theatre_partners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `theatre_partner_id_idx` ON `theatre` (`theatre_partner_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `theatre_halls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theatre_halls` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `theatre_halls` (
  `id` INT(11) NOT NULL,
  `theatre_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `seating_plan_id` INT(11) UNSIGNED NOT NULL,
  `description` TEXT NOT NULL,
  `security_checklist` TEXT NOT NULL,
  `supported_movie_experience` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `theatre_id`
    FOREIGN KEY (`theatre_id`)
    REFERENCES `theatre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seating_plan_id`
    FOREIGN KEY (`seating_plan_id`)
    REFERENCES `seating_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `theatre_id_idx` ON `theatre_halls` (`theatre_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `seating_plan_id_idx` ON `theatre_halls` (`seating_plan_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `theatre_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theatre_manager` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `theatre_manager` (
  `id` INT(11) NOT NULL,
  `theatre_id` INT(11) UNSIGNED NOT NULL,
  `user_profile_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `theatre_id`
    FOREIGN KEY (`theatre_id`)
    REFERENCES `theatre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_profile_id`
    FOREIGN KEY (`user_profile_id`)
    REFERENCES `user_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `theatre_id_idx` ON `theatre_manager` (`theatre_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_profile_id_idx` ON `theatre_manager` (`user_profile_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `theatre_partner_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theatre_partner_account` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `theatre_partner_account` (
  `id` INT(11) NOT NULL,
  `theatre_partner_id` INT(10) UNSIGNED NOT NULL,
  `account_id` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `theatre_partner_id`
    FOREIGN KEY (`theatre_partner_id`)
    REFERENCES `theatre_partners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `theatre_partner_id_idx` ON `theatre_partner_account` (`theatre_partner_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `account_id_idx` ON `theatre_partner_account` (`account_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `theatre_partners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theatre_partners` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `theatre_partners` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `alias_name` VARCHAR(255) NOT NULL,
  `owner_details` VARCHAR(255) NOT NULL,
  `contact_number` VARCHAR(20) NOT NULL,
  `head_office_location_id` INT(10) UNSIGNED NOT NULL,
  `supporting_documents` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `location_id`
    FOREIGN KEY (`head_office_location_id`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `theatre_partners` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `theatre_partners` (`name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `alias_name_UNIQUE` ON `theatre_partners` (`alias_name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `theatre_partners` (`email` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `location_id_idx` ON `theatre_partners` (`head_office_location_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_profile` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_profile` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `contact_number` VARCHAR(20) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
